### ISSUE TITLE
How to train Leo on other datasets ?

### ISSUE THREAD

**Issue by peterdarkdarkgogo** [timchen0618/pytorch-leo#2]
How to train Leo on other datasets ? Thanks

**Comment by timchen0618** [comment]
Hi @peterdarkdarkgogo, the pretrained embedding features are originally provided by LEO authors. If you would like to train on other datasets, the most straightforward approach is to follow section 4.2.2 in the paper to generate features on your own. We don't have the resources to provide pretrained features ourselves. Thank you!
